name: Deploy VitePress site to Pages

on:
  # 在针对 `docs` 分支的推送上运行
  push:
    branches:
      - docs

jobs:
  # 构建工作
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # 设置为完整地获取整个仓库历史记录以支持 VitePress 的生成静态站点
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install # 根据你的项目使用 npm、pnpm 或 yarn
      - name: Build VitePress
        run: npm run docs:build # 根据你的项目设置执行 VitePress 的构建命令
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          cname: atqingke.com # 如果有自定义域名，可以设置在这里

